#!/bin/sh
# Pre-publication check on the tracked tree. It refuses three kinds of content that belong to the
# machines this project is built on rather than to the project itself:
#
#   1. the address or tooling of a private host, which a clone can neither reach nor audit;
#   2. a path into a working note, which no clone contains, so a reference to one is a dead end;
#   3. prose narrating how the code came to be rather than what it does or why it holds.
#
# Every hit prints as `path:line: pattern` and the script exits non-zero. A hit is a sentence to
# rewrite or a file to drop, never a pattern to weaken.
#
# It is a pre-publication tool, run by a person against the tree that is about to be published,
# and deliberately not wired into CI: the tree CI runs on is the working one, which legitimately
# carries configuration no published clone would.
#
# Scope is the tracked files. Fixture data is fetched corpus text, cassettes are recorded model
# output, and the goldens under `tests/output/golden/` and `tests/site_/golden/` are rendered
# output holding quoted corpus text; all three are verbatim or generated by rule and are never
# rewritten to satisfy a grep, so all three are out of scope. So is this file, whose pattern list
# necessarily contains every string it forbids.
#
# A named exemption list sits below the search helpers. Each entry pins one file, one pattern and
# the text that carries it, with the reason that text is not narrative, so a reader can re-judge
# every exemption without leaving the script. An exemption that matches nothing fails the run: the
# list describes the tree or it is deleted. The fourteen entries were reviewed on 2026-08-14 and
# every one is a listed phrase used in its legal or data sense: nine are strings the code ships
# (prompt literals the model is sent, a skip reason, two field descriptions, two operator
# messages, one dated caveat) and five are the tests that assert those strings verbatim. Rewriting
# any of them would change what the code sends or prints, and re-key the recordings the published
# figures are measured over. The standing rule is unchanged and this list is not an escape from
# it: a new hit is a sentence to rewrite or a file to drop, never a line to add here.
set -eu

cd "$(git rev-parse --show-toplevel)"

hits=$(mktemp)
raw=$(mktemp)
exempt=$(mktemp)
used=$(mktemp)
trap 'rm -f "$hits" "$raw" "$exempt" "$used"' EXIT HUP INT TERM

# Search the tracked tree for one pattern. Arguments: grep flags, the pattern, a regex whose
# matches are struck from a line before the pattern is retested (empty for none), then any
# pathspecs narrowing or further excluding the search.
record() {
    flags=$1
    pattern=$2
    allow=$3
    shift 3
    status=0
    git grep -nI -E $flags -e "$pattern" -- "$@" \
        ':(exclude)tests/fixtures/' \
        ':(exclude)tests/cassettes*' \
        ':(exclude)tests/output/golden/' \
        ':(exclude)tests/site_/golden/' \
        ':(exclude)scripts/public_leak_check.sh' >"$raw" || status=$?
    # 1 is "no hits" and is the good case. Anything above it is a broken pattern or pathspec,
    # which would otherwise turn this check into a silent no-op, so it stops the run instead.
    if [ "$status" -gt 1 ]; then
        printf 'search failed for pattern: %s\n' "$pattern" >&2
        exit 2
    fi
    ALLOW="$allow" PAT="$pattern" awk -v exempt="$exempt" -v used="$used" '
        BEGIN {
            FS = ":"
            allow = ENVIRON["ALLOW"]
            pat = ENVIRON["PAT"]
            # Only the exemptions written against this pattern can silence a line of it.
            while ((getline entry < exempt) > 0) {
                split(entry, field, "\t")
                if (field[2] != pat) continue
                count++
                ex_path[count] = field[1]
                ex_text[count] = field[3]
            }
            close(exempt)
        }
        {
            path = $1
            line = $2
            text = substr($0, length(path) + length(line) + 3)
            if (allow != "") {
                stripped = text
                gsub(allow, "", stripped)
                if (stripped !~ pat) next
            }
            for (i = 1; i <= count; i++) {
                if (path == ex_path[i] && text ~ ex_text[i]) {
                    printf "%s\t%s\n", path, pat >>used
                    next
                }
            }
            printf "%s:%s: %s\n", path, line, pat
        }
    ' "$raw" >>"$hits"
}

scan() { record "" "$@"; }
# Whole words, either case: these are prose phrases and a sentence may capitalise the first one.
scan_prose() { record "-w -i" "$@"; }

# Exempt one line from one pattern. Arguments: the file, the pattern exactly as the scan below
# spells it, a regex the line must match, and the reason that line is not narrative. Scoping an
# exemption to a file and a pattern and the text carrying it is deliberate: a new sentence in the
# same file still fails the check unless it repeats the exempted wording, which is the loosest
# form this list takes. The reason is data, not a comment, so a stale entry can name itself.
exempt() { printf '%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" >>"$exempt"; }

exempt 'src/emendrix/explain/prompt.py' 'earlier version' \
    'this provision did not exist in the earlier version' \
    'prompt literal: the earlier consolidated version of the act, sent to the model'
exempt 'src/emendrix/explain/prompt.py' 'earlier version' \
    'this provision existed in the earlier version and is gone' \
    'prompt literal: what DELETED means to the model, in the same sense'
exempt 'src/emendrix/explain/prompt.py' 'previously' \
    'PREVIOUSLY NUMBERED' \
    'prompt field label for a provision that moved to a different number'
exempt 'src/emendrix/graph/stages.py' 'earlier version' \
    'no earlier version of this act to compare against' \
    'shipped skip reason: the corpus holds one version of the act, not two'
exempt 'src/emendrix/eval_/benchmark.py' 'superseded' \
    'Delete the superseded recording' \
    'operator message about two recordings of one judged prompt'
exempt 'src/emendrix/eval_/benchmark_cli.py' 'superseded' \
    'recorded on 2026-08-08 and superseded the same day' \
    'dated provenance of the label set, and the caveat that it is not what ships'
exempt 'src/emendrix/eval_/model_metrics.py' 'no longer' \
    "Pinned units this run's delta no longer contains" \
    'field description: what the metric counts, in the present tense'
exempt 'src/emendrix/eval_/model_report.py' 'no longer' \
    "Pinned units this run's deltas no longer contain" \
    'the same field, rendered into the report'
exempt 'src/emendrix/eval_/prose.py' 'no longer' \
    'what it no longer does is report every unit' \
    'dated record of what the disputed signal reports, which the figures depend on'
exempt 'tests/eval/test_benchmark.py' 'superseded' \
    'Delete the superseded recording' \
    'asserts the operator message above verbatim'
exempt 'tests/explain/test_prompt.py' 'earlier version' \
    'this provision did not exist in the earlier version' \
    'asserts the prompt literal above verbatim'
exempt 'tests/explain/test_prompt.py' 'earlier version' \
    'this provision existed in the earlier version and is gone' \
    'asserts the prompt literal above verbatim'
exempt 'tests/explain/test_prompt.py' 'previously' \
    'PREVIOUSLY NUMBERED' \
    'asserts the prompt field label above verbatim'
exempt 'tests/graph/test_pipeline_toy.py' 'earlier version' \
    'no earlier version" in final' \
    'asserts the shipped skip reason above'

# Infrastructure.
scan 'fprog\.club' ''
scan 'fprog-registry-secret' ''
scan 'registry\.[a-z0-9-]+\.[a-z][a-z]+' ''
scan 'Hetzner' ''
scan 'emendrix-deploy' ''
scan 'k3s' ''
scan 'cloudflared' ''
scan 'kustomize' ''
scan 'KUBECONFIG' ''
scan '[Gg]itea' ''
# The site's own published address, allowed where the deployment configures it, where the
# documentation tells a reader what to visit, and as the package's `Homepage`.
scan 'symber\.net' '' ':(exclude)deploy/compose.yaml' ':(exclude)README.md' ':(exclude)docs/' \
    ':(exclude)pyproject.toml'
# The author's name, allowed where authorship is the point and where a review record names the
# person who signed it, including the published table and the site page generated from it.
scan 'Martins Erts' '' ':(exclude)LICENSE' ':(exclude)pyproject.toml' ':(exclude)reports/' \
    ':(exclude)README.md' ':(exclude)tests/site_/golden/'

# Working notes. `.gitignore` is out of scope for this group: an ignore entry naming a working
# note is the rule that keeps it out of the tree, and deleting the entry to satisfy a grep would
# let the next one in.
notes() { scan "$1" '' ':(exclude).gitignore'; }
notes 'temp/'
notes 'HANDOFF'
notes '\.superpowers'
notes '\.claude'
notes 'CLAUDE\.md'
notes 'docs/plans/'
notes 'docs/specs/'
notes '[Ss]tep [0-9]'
notes '[Tt]ask [0-9]'

# Development narrative. This group skips `reports/` and `CHANGELOG.md`: a review sheet records
# what a person concluded and a changelog records what changed, and both are legitimately written
# in the past tense.
narrative() { scan_prose "$1" '' ':(exclude)reports/' ':(exclude)CHANGELOG.md'; }
narrative 'it turned out'
narrative 'was first written'
narrative 'cost .* commits'
narrative 'observed on'
narrative 'previously'
narrative 'used to'
narrative 'originally'
narrative 'at first'
narrative 'earlier version'
narrative 'the first attempt'
narrative 'this was proven'
narrative 'superseded'
narrative 'no longer'
# First person reads as narrative in the project's own prose, but quoted legal text and
# corpus-derived strings use both words for their own reasons, so this pair is scoped tighter.
scan_prose 'we' '' 'src/' 'tests/'
scan_prose 'our' '' 'src/' 'tests/'

failed=0

# An exemption nothing matched is an exemption nobody has read against the current tree, and it is
# how a list stops describing the thing it exempts. It fails the run so it gets re-judged.
stale=$(awk -F'\t' -v used="$used" '
    FILENAME == used { seen[$1 "\t" $2] = 1; next }
    !(($1 "\t" $2) in seen) { printf "  %s [%s]: %s\n", $1, $2, $4 }
' "$used" "$exempt")
if [ -n "$stale" ]; then
    printf 'Exemptions matching nothing. Re-read the file and delete the entry:\n%s\n\n' "$stale"
    failed=1
fi

if [ -s "$hits" ]; then
    sort -t: -k1,1 -k2,2n "$hits"
    printf '\n%s hits. This tree is not ready to publish.\n' "$(wc -l <"$hits" | tr -d ' ')"
    failed=1
fi

[ "$failed" -eq 0 ] || exit 1
printf 'Clean: no private host, working note or development narrative in the tracked tree.\n'
